spin_manifest_version = 2

[application]
name = "app"
version = "0.1.0"
authors = ["Uriah <codeitlikemiley@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "app"

[component.app]
source = "target/wasm32-wasip1/release/app.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
# models: llama2-chat and codellama-instruct, all-minilm-l6-v2
# https://developer.fermyon.com/spin/v3/ai-sentiment-analysis-api-tutorial
ai_models = ["llama2-chat"]

[component.app.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]