spin_manifest_version = 2

[application]
name = "app"
version = "0.1.0"
authors = ["Uriah <codeitlikemiley@gmail.com>"]
description = ""

[variables]
env = { default = "dev" }

[[trigger.http]]
route = "/..."
component = "app"

[component.app]
source = "target/wasm32-wasip1/release/app.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
sqlite_databases = ["default"]

[component.app.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
